models_path:
  unet: "/home/interactdiff-diffusers/models/unet"
  vae: "/home/interactdiff-diffusers/models/vae"
  text_encoder: "/home/interactdiff-diffusers/models/text_encoder"
  scheduler: "/home/interactdiff-diffusers/models/scheduler"

training_params:
  lr: 5e-5
  weight_decay: 0.0
  lr_warmup_steps: 10000
  scheduler_type: 'constant'
  amp_enabled: False
  batch_size: 4
  num_workers: 1
  num_iterations: 100

train_dataset_names:
  HicoDetHOI:
    which_layer_text: before
    image_size: 512
    max_boxes_per_data: 30
    prob_use_caption: 0.5
    random_crop: False

